### ISSUE TITLE
`exists` doesn't work?

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool-binding#10]
I tried using the `exists` feature, but I can't get it to work. I checked the sources, and I don't see how it would work currently. The function name (e.g. for `graphcool.exists.user(...)` that would be `user`) is passed in as rootFieldName, but that doesn't exist, and the generated info object contains a different `rootFieldName`, which I think is also incorrect, because it should only contain the field selection. Also, it doesn't use proper pluralization, so it will fail there as well for all types ending in -o (`Potato` -> `allPotatoes`, not `allPotatos`).

**Comment by marktani** [comment]
Currently, it's `exists.users`.

Also see https://github.com/graphcool/graphcool-binding/issues/3

**Comment by kbrandwijk** [comment]
I strongly doubt that, as that would turn the query into `alluserss`. Then again, the only reason that would work is because the rootFieldName is actually not used internally in `delegateToSchema`...

**Comment by marktani** [comment]
The 1.0 API does not have a `allUsers` query. It is called `users`.

**Comment by kbrandwijk** [comment]
No longer an issue.
