### ISSUE TITLE
Feature Request:  Codegen'd resolvers

### ISSUE THREAD

**Issue by LawJolla** [graphcool/graphcool-binding#14]
First, amazing job and I'm one of your biggest fans!  I hand coded a GraphQL server with user accounts and auth.  Never again, especially when there's GraphCool!

One of the biggest GraphQL pain points is the sheer amount of boilerplate.  I enjoyed not writing resolvers with GraphCool.  The 1.0 version requires a server, which I love, but it brings back some resolver boilerplate.  I would love to see some method of automatically generating resolvers from the CRUD API.  Perhaps from the CLI?

e.g.

`graphcool magically-add-user-resolver-for-create --at index.js` and in my index.js I find:

```
 Mutation: {
   ...
    createUser(parent, { name }, ctx, info) {
      return ctx.db.mutation.createUser(
        { data: { name } },
        info,
      )
    },
```

Thank you and keep up the amazing work!

**Comment by kbrandwijk** [comment]
Thank you for this feedback. There are different ways to improve this. Having these bindings generated so you can easily call existing queries and mutations is the first step towards that goal.

One of the options I am personally looking at is a way to 'extend' on what `graphql-import` offers to also work on resolvers (basically saving you from having to define this resolvers manually completely). However, looking at common use cases, it didn't seem that common to reuse existing queries or mutations exactly 1-on-1.

**Comment by kbrandwijk** [comment]
@LawJolla We have implemented `forwardTo` in the latest release. Examples are coming, but you can basically replace your resolver function with a simple `forwardTo('db')` if you want to forward a call 1-on-1 (so same query name and arguments) to an underlying binding. See https://gist.github.com/kbrandwijk/6e693f1cad585cb74fd8e022c7277394#file-query-ts-L11 for a small snippet. Do you think that this sufficiently covers your use case?

**Comment by LawJolla** [comment]
I think that hits the use case dead on!  Great implementation!  Makes a ton of sense.  Thanks for your hard and great work!

**Comment by marktani** [comment]
Here's an example: https://github.com/graphcool/graphcool/tree/examples-1.0/examples/resolver-forwarding 🙂

**Comment by kbrandwijk** [comment]
Closing, as this use case is apparently sufficiently covered by this feature.
