### ISSUE TITLE
JSON Type not allowed on application schema

### ISSUE THREAD

**Issue by davidyin1212** [graphcool/graphcool-binding#15]
Currently when I set the field type to Json in the application schema I get `Error: Field rules: Couldn't find type Json`. However this type works in the database schema

**Comment by kbrandwijk** [comment]
You should be able to add `scalar Json` to your final schema, but I'm not sure how to add the corresponding resolver.

**Comment by schickling** [comment]
@davidyin1212 is this still an issue for you or was this solved by the newest version?

**Comment by schickling** [comment]
Closing for now. Please re-open when this is still an issue.
