### ISSUE TITLE
Invalid selection set should throw error

### ISSUE THREAD

**Issue by sorenbs** [graphcool/graphcool-binding#18]
This query has a invalid selection set. (`logins` should be `login`)

```
ctx.db.query.user({ where: { id: userId } }, '{ logins { id } }')
```

Currently this generates an invalid query:

```
1: query ($_where: UserWhereUniqueInput!) {
2:   user(where: $_where) {}
                           ^
3: }
```

It would be better to throw an exception

This issue is related to but different from #16

**Comment by schickling** [comment]
Fixed in newest version.
