### ISSUE TITLE
Settle API for `exists`

### ISSUE THREAD

**Issue by nikolasburk** [graphcool/graphcool-binding#3]
It feels a bit unnatural to use `exists` as follows:

```js
ctx.db.exists.comments({
      writtenBy: {
        id: userId
      }
    })
```

What should the generated functions on `exists` be named?

**Comment by kbrandwijk** [comment]
I think the more natural way would be: `db.Comment.exists(...)`. So use the type name instead of the query root field, and turn it around, in a Fluent API style.

**Comment by kbrandwijk** [comment]
This is implemented in the latest version: `db.exists.Comment({ ... })`. Can this be closed for now?

**Comment by marktani** [comment]
yep! 😄

**Comment by heymartinadams** [comment]
Just an idea, perhaps for consistency’s sake? Both queries and mutations use `where: {...}`: it would be helpful to keep that pattern for `db.exists`.

**Comment by schickling** [comment]
@heymartinadams do you have any other arguments besides `where` in mind that should go there?

**Comment by heymartinadams** [comment]
No, @schickling. But as someone who’s still a little green behind his ears when it comes to GraphQL, I might not be the right person to ask 😉
