### ISSUE TITLE
Create 'passthrough' resolvers for 1-on-1 delegation to underlying schema

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool-binding#45]
## Passthrough resolvers
In the current implementation, exposing root fields from one of the bindings in the final schema is a bit involved, because you need to:

- Add the field to your schema (1)
- Implement a resolver that delegates to the correct field on the binding (2)

This introduces a lot of duplication and boilerplate. This proposal addresses this.

## Implementation details
To make step (1) easier, there will also be a proposal on `graphql-import` to support importing root fields using the existing `# import` syntax (-- insert link here --)
For step (2), the minimal setup requires at least to define the resolver, and specify which binding to pass through to. So the resolver could look like this:

```
const resolver = {
  Query: {
    posts: passthrough('database')
  }
}
```
With 'database' being the name of the binding, and passthrough being an exported function from `graphcool-binding` (or maybe re-exported from `graphql-binding`) that translates into the right resolver.
Based on the available information at runtime in the `parent` and `info` parameters, combined with the name of the binding, all information should be available to do this.

**Comment by schickling** [comment]
Awesome work @kbrandwijk! @marktani will soon create some examples for this feature.

**Comment by kbrandwijk** [comment]
Here's a minimal rundown of how to use it: https://gist.github.com/kbrandwijk/6e693f1cad585cb74fd8e022c7277394
