### ISSUE TITLE
"Schema must be an instance of GraphQLSchema." when creating subscription binding

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-binding#54]
Executing this subscription resolver

```js
  Subscription: {
    publications: {
      subscribe: async(parent, args, ctx, info) => {
        return ctx.db.subscription.post({}, info)
      },
    },
  }
```

leads to this error:

> Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.

See https://github.com/marktani/reproduction-subscriptions for a complete reproduction.

**Comment by kbrandwijk** [comment]
I am unable to reproduce this with these dependency versions:
```
"dependencies": {
    "graphcool-binding": "1.3.5",
    "graphql-yoga": "1.1.7"
  },
  "devDependencies": {
    "graphcool": "^1.0.0-alpha4.2.4"
  }
```

**Comment by schickling** [comment]
This looks like a problem with @marktani's local setup. For everyone running into this problem, please try to delete the `node_modules` folder and reinstall via `npm` or `yarn`.

Please be aware that this can be especially a problem when linking node modules. I recommend using yarn workspaces in that case.
