### ISSUE TITLE
Transforming an incoming selection set before passing it into a resolver

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-binding#61]
Say I have the following `datamodel.graphql`:

```graphql
type Link {
  id: ID!
  url: String!
}
```

and the following `schema.graphql`:

```graphql
# import Link from "./generated/graphcool.graphql"

type Query {
  feed: Feed!
}

type Feed {
  links: [Link!]!
  count: Int!
}
```

This is how my resolver currently looks like:

```ts
async function feed(parent, args, ctx, info) {
  const allLinks = await ctx.db.query.links({})
  const count = allLinks.length


  // pick the selection set 
  const linksSelections = info.operation.selectionSet.selections[0].selectionSet.selections[0]
  const queriedLinkes = await ctx.db.query.links({ }, linksSelections)

  return {
    links: queriedLinkes,
    count
  }
}
```

This works now, but it looks like a bad approach in general. I also think the the `pick the selection set` line only works for specific queries.

Is there a more elegant solution for transforming an incoming `info` object before passing it into a resolver? 🙂

**Comment by marktani** [comment]
The answer is to return an object with two fields `links` and `count`. The `links` field is another resolver again:

```ts
async function feed(parent, args, ctx, info) {
  const allLinks = await ctx.db.query.links({})
  const count = allLinks.length
  const queriedLinkes = await ctx.db.query.links({ }) // don't pass info!

  return {
    links: queriedLinkes,
    count
  }
}
```

**Comment by maticzav** [comment]
Instead of defining `feed`- field resolver, you should define `feed` type resolver.
```typescript
// Feed.ts
import { Context } from '../utils'

export const Feed = {
   async links(parent, args, ctx: Context, info) {
      return ctx.db.query.links({}, info)
   },
   async count(parent, args, ctx: Contextn, info) { // <- C (parent argument)
      const connections = await ctx.db.query.linksConnection({} , ` { aggregate { count } } `)
      return connections.aggregate.count
   }
}

// resolvers.ts
import { Feed } from './Feed'

export const resolvers = {
   Query: {
      feed: () => ({}), // <- A
   },
   Feed,
}
```
🤞 everything's ok, I have written it here 😄 

Bit of explanation: 
 - what `A` does is pass no property to Feed resolver. If we were to pass any property down, `a:  'foo'`, for example, like this `feed: () => ({ a: 'foo' })`, the `parent` argument (`C`) would, instead of `{}` have value `{ a: 'foo' }`.
